version: '3.4'

services:
  kubeweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  kubeapimongo:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "83:80"


  kubeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"


  kubeapisqlserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "82:80"

