apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment  # change this to rename deployment
spec:
  selector:
    matchLabels:
      app: nginx  # this must match template metadata 
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx # this must match --- matchLabels
    spec:
      containers:
      - name: nginx  # just the name of the container
        image: nginx:1.14.2
        ports:
        - containerPort: 80