apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sqldata
  name: sqldata
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqldata
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sqldata
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: Y
        - name: SA_PASSWORD
          value: tvxs721#3
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: ""
        name: sqldata
        ports:
        - containerPort: 1433
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: db3-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: db3-data
        persistentVolumeClaim:
          claimName: db3-data
status: {}
